#!/usr/bin/env python
# Challenge1 - Write a script that builds three 512 MB Cloud Servers that
# following a similar naming convention. (ie., web1, web2, web3) and returns
# the IP and login credentials for each server. Use any image you want.
# Author: Scott Gilbert

import os
import time
import pyrax

# unbuffer stdout
import sys
sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', 0)

credential_file=os.path.expanduser("~/.rackspace_cloud_credentials")
# 512MB
flavor = 2 
# CentOS 6.3
image = 'c195ef3b-9195-4474-b6f7-16e5bd86acd0'

pyrax.set_credential_file(credential_file)
cs = pyrax.cloudservers
server=[]

# Request build of new servers
for server_num in xrange(1,4):
  print "Requesting build for server web%d" % server_num
  server.append(cs.servers.create("web%d" % server_num, image, flavor))

# Wait for all servers to get network info assigned
print "\nWaiting for Networking info to be assigned..."
build_done = False
while not build_done:
  time.sleep(2)
  print ".", 
  build_done = True
  for srv in server:
    srv.get()
    if srv.networks == {}:  
      build_done = False
      break

# Print all the happy goodness!
print "Done!\n"
for srv in server:
  print
  print "Server Name:", srv.name
  print "Root Password:", srv.adminPass
  print "Public IPs:", 
  for ip in srv.networks['public']: print ip, '  ',
  print
  print "Private IP:", 
  for ip in srv.networks['private']: print ip, '  ',
  print


