#!/usr/bin/env python
# Challenge2 - Write a script that clones a server (takes an image and deploys
# the image as a new server). 

# Accepts a single parameter of the uuid of the server to be cloned.

import os
import time
import pyrax

credential_file=os.path.expanduser("~/.rackspace_cloud_credentials")
pyrax.set_credential_file(credential_file)
cs = pyrax.cloudservers

def cloneIt(serverUUID):
  # get info about source server
  source_server = cs.servers.get(serverUUID)

  # Request image of source server
  image_id = cs.servers.create_image(serverUUID, source_server.name + '-img')

  # Wait for image to complete
  print "Waiting for image build to complete..."
  while cs.images.get(image_id).status <> 'ACTIVE':
    time.sleep(60)
    print cs.images.get(image_id).status

  # Create new server using image 
  newserver = cs.servers.create(source_server.name + '-clone', image_id,
                                source_server.flavor['id'])

  # Wait for network info to become available
  print "Waiting for new server build..."
  while cs.servers.get(newserver.id).networks == {}:
    time.sleep(5)

  # Print info for new server
  print
  srvr = cs.servers.get(newserver.id)
  print "Server Name:", srvr.name
  print "Root Password:", newserver.adminPass
  print "Public IPs:", 
  for ip in srvr.networks['public']: print ip, '  ',
  print
  print "Private IP:", 
  for ip in srvr.networks['private']: print ip, '  ',
  print


if __name__ == "__main__":
  import sys

  if len(sys.argv) == 2:
    cloneIt(sys.argv[1]);
  else:
    print "Wrong number of parameters specified!"
    print "Usage:  challenge2 <server uuid>"

# vim: ts=2 sw=2 tw=78 expandtab
